services:
  # Service pour le backend
  - type: web
    name: mini-stack-backend
    env: node
    buildCommand: cd server && npm run build
    startCommand: cd server && npm run deploy
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Vous devrez configurer cette variable dans le dashboard Render
      - key: JWT_SECRET
        sync: false # Vous devrez configurer cette variable dans le dashboard Render
    autoDeploy: true

  # Service pour le frontend
  - type: web
    name: mini-stack-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://mini-stack-backend.onrender.com # Remplacez par l'URL de votre backend
    autoDeploy: true
