name: CI - Build & Publish

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build client (Vite)
        working-directory: ./client
        run: |
          npm ci
          npm run build

      - name: Upload client artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: client/dist/

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mini-stack-overflow-server:latest
            ghcr.io/${{ github.repository_owner }}/mini-stack-overflow-server:${{ github.sha }}

  # Optional: a job to run integration tests could be added here
